## Image name: faucet/faucet-testbase
## Base image for FAUCET tests.

FROM ubuntu:latest

ENV OVSV="master"
ENV DPDK="17.11"
ENV MININETV="2.2.2"

ENV OVSDEPS="autoconf automake libpcap-dev libcap-ng-dev libnuma-dev libtool libssl-dev linux-headers-generic libffi-dev"
ENV AG="apt-get -qqy --no-install-recommends -o=Dpkg::Use-Pty=0"
ENV DEBIAN_FRONTEND=noninteractive
ENV PIPDEPS="setuptools wheel virtualenv"
ENV PIP="pip -q --no-cache-dir install --upgrade"
ENV PIP3="pip3 -q --no-cache-dir install --upgrade"
ENV SETUPQ="setup.py -q"
ENV MAKEFLAGS="-s -j -l 2.0"
ENV BUILDDIR="/var/tmp/build"

###
### When apt-get'ing, make sure apt-update always run first per RUN
### to ensure Docker layer cache doesn't use a stale apt database.
###

COPY setupproxy.sh /

RUN \
  ./setupproxy.sh && \
  $AG update && \
  $AG install \
    $OVSDEPS \
    apt-transport-https \
    bc \
    bridge-utils \
    build-essential \
    curl \
    fping \
    gcc \
    git \
    iperf \
    iputils-ping \
    iproute2 \
    ladvd \
    libnuma-dev \
    libpython2.7-dev \
    libpython3-dev \
    libyaml-dev \
    lsof \
    netcat \
    ndisc6 \
    net-tools \
    netcat-openbsd \
    numactl \
    openvswitch-common \
    parallel \
    patch \
    psmisc \
    python-pip \
    python3-pip \
    software-properties-common \
    sudo \
    tcpdump \
    tshark \
    vlan \
    wget \
    wpasupplicant && \
  $AG install linux-headers-`uname -r` && \
  git config --global url.https://github.com/.insteadOf git://github.com/ && \
    mkdir -p $BUILDDIR && \
    cd $BUILDDIR && \
    wget -q -O- http://fast.dpdk.org/rel/dpdk-$DPDK.tar.xz | tar -Jxf- && \
      cd dpdk* && \
      export DPDK_DIR=`pwd` && \
      export DPDK_TARGET=x86_64-native-linuxapp-gcc && \
      make install T=$DPDK_TARGET DESTDIR=install && \
    cd .. && \
    git clone https://github.com/openvswitch/ovs -b ${OVSV} && \
      cd ovs && \
      ./boot.sh && \
      ./configure --enable-silent-rules --quiet --with-dpdk=$DPDK_DIR/$DPDK_TARGET && \
      make install && \
    cd .. && \
    git clone https://github.com/mininet/mininet -b $MININETV && \
      cd mininet && \
      perl -pi -e "s/setup.py/${SETUPQ}/g" Makefile && \
      perl -pi -e "s/apt-get/${AG}/g" util/install.sh && \
      for i in ssh pep8 pyflakes python-pexpect pylint xterm ; do \
          perl -pi -e "s/${i}//g" util/install.sh ; done && \
      util/install.sh -n && \
    cd .. && \
    git clone https://github.com/google/pytype.git && \
      cd pytype && \
      git checkout 0964db4d6683324035486109a5ea6c210d8b131c && \
      git submodule init && \
      git submodule update && \
      python2 $SETUPQ install && \
    cd .. && \
  cd / && rm -rf $BUILDDIR && \
  $AG purge $OVSDEPS linux-headers-`uname -r` && \
  $AG autoremove

RUN \
  ./setupproxy.sh && \
  $AG update && \
  $AG purge pylint && \
  $PIP3 pip && \
  easy_install -q -U pip && \
  $PIP pip && \
  $PIP multiprocessing scapy==2.3.2 $PIPDEPS && \
  $PIP3 $PIPDEPS
