## Image name: faucet/config-fuzzer

FROM faucet/test-base:8.0.6

ENV PIP3="pip3 --no-cache-dir install --upgrade"
ENV PATH="/venv/bin:$PATH"

COPY ./ /faucet-src/
WORKDIR /faucet-src

RUN \
  apt-get update && \
  apt-get install -y afl cython3 && \
  $PIP3 pip setuptools && \
  $PIP3 -r requirements.txt && \
  $PIP3 -r fuzz-requirements.txt && \
  $PIP3 .

VOLUME ["/var/log/afl/"]

CMD ["docker/fuzz_config.sh"]
