## Image name: faucet/gauge-pi

FROM faucet/faucet-python3-pi

COPY ./ /faucet-src/

RUN ./faucet-src/docker/base/install-faucet.sh

VOLUME ["/etc/ryu/faucet/", "/var/log/ryu/faucet/"]

EXPOSE 6653 9303

CMD ["ryu-manager", "faucet.gauge"]
