## Image name: faucet/faucet

FROM c65sdn/python3:1.0.4

COPY ./ /faucet-src/

RUN rm -f rm /usr/bin/lsb_release
RUN ./faucet-src/docker/install-faucet.sh

VOLUME ["/etc/faucet/", "/var/log/faucet/", "/var/run/faucet/"]

EXPOSE 6653 9302

CMD ["faucet"]
