FROM osrg/ryu

RUN \
  apt-get update && \
  apt-get install -qy --no-install-recommends python-pip

ADD ryu-faucet-dev.tar.gz /

RUN \
  pip install ipaddr; \
  pip install /ryu-faucet-dev.tar.gz

VOLUME ["/etc/opt/faucet/", "/var/log/faucet/"]
WORKDIR /usr/local/lib/python2.7/dist-packages/ryu_faucet/org/onfsdn/faucet/

EXPOSE 6633

CMD ["ryu-manager", "--verbose", "--ofp-tcp-listen-port=6633", "faucet"]
