{
 "title": "Faucet Port Statistics",
 "tags": [ "FAUCET" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dp_name",
    "label": "Datapath Name",
    "query": "label_values(of_port_rx_bytes, dp_name)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "query_result(port_status{dp_name =~ \"$dp_name\"} == 1)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bits in/out per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "instance_port:of_port_rx_bits:rate1m{dp_name=~\"[[dp_name]]\", port=~\"[[port]]\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dp_name}} port {{port}} ({{port_description}}) in",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "instance_port:of_port_tx_bits:rate1m{dp_name=~\"[[dp_name]]\", port=~\"[[port]]\"} * -1",
     "legendFormat": "{{dp_name}} port {{port}} ({{port_description}}) out"
    }
   ]
  },
  {
   "title": "Packets in/out per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "instance_port:of_port_rx_packets:rate1m{dp_name=~\"[[dp_name]]\", port=~\"[[port]]\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dp_name}} port {{port}} ({{port_description}}) in",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "instance_port:of_port_tx_packets:rate1m{dp_name=~\"[[dp_name]]\", port=~\"[[port]]\"} * -1",
     "legendFormat": "{{dp_name}} port {{port}} ({{port_description}}) out"
    }
   ]
  },
  {
   "title": "Dropped in/out per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "instance_port:of_port_rx_dropped:rate1m{dp_name=~\"[[dp_name]]\", port=~\"[[port]]\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dp_name}} port {{port}} ({{port_description}}) in",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "instance_port:of_port_tx_dropped:rate1m{dp_name=~\"[[dp_name]]\", port=~\"[[port]]\"} * -1",
     "legendFormat": "{{dp_name}} port {{port}} ({{port_description}}) out"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "instance_port:of_port_rx_errors:rate1m{dp_name=~\"[[dp_name]]\", port=~\"[[port]]\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{dp_name}} port {{port}} ({{port_description}}) in",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}